ProjectMedic/Controllers/VisitByDoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectMedic.Models;
using System.Data.Entity;
using PagedList;

namespace ProjectMedic.Controllers
{
    public class VisitByDoctorController : Controller
    {
        MediPlusEntities db = new MediPlusEntities();
        // GET: VisitByDoctor
        public ActionResult Index(int? page_no, string search, string ddl1, string ddl2, string ddl3)
        {
            if (Session["P_ID"] == null)
            {
                return RedirectToAction("TermOfService", "Home");
            }

            Session["action"] = "selectdoctor";

            List<SelectListItem> list1 = new List<SelectListItem>();
            list1.Add(new SelectListItem { Text = "View All", Value = "refresh" });
            list1.Add(new SelectListItem { Text = "Male", Value = "Male" });
            list1.Add(new SelectListItem { Text = "Female", Value = "Female" });

            List<SelectListItem> list2 = new List<SelectListItem>();
            list2.Add(new SelectListItem { Text = "View All", Value = "refresh" });
            foreach (var item in db.Academic_Title)
            {
                list2.Add(new SelectListItem()
                {
                    Text = item.AcademicTitle_Means.ToString(),
                    Value = item.AcademicTitle_Code.ToString()
                });
            }

            List<SelectListItem> list3 = new List<SelectListItem>();
            list3.Add(new SelectListItem { Text = "View All", Value = "refresh" });
            foreach (var item in db.Medical_Specialty)
            {
                list3.Add(new SelectListItem()
                {
                    Text = item.MedicalSpecialty_Name.ToString(),
                    Value = item.MedicalSpecialty_Name.ToString()
                });
            }

            ViewBag.Gender = list1;
            ViewBag.AcademicTitle = list2;
            ViewBag.MedicalSpecialty = list3;

            var doctors = db.vDoctors.AsQueryable();
            
            if (!String.IsNullOrEmpty(search))
            {
                doctors = doctors.Where(d => d.Doctor_Name.Contains(search));
            }

            if (ddl1 != null && ddl1 != "refresh")
            {
                doctors = doctors.Where(d => d.Doctor_Gender.Equals(ddl1));
            }

            if (ddl2 != null && ddl2 != "refresh")
            {
                doctors = doctors.Where(d => d.AcademicTitle_Code.Equals(ddl2));
            }

            if (ddl3 != null && ddl3 != "refresh")
            {
                doctors = doctors.Where(d => d.MedicalSpecialty_Name.Equals(ddl3));
            }

            return View(doctors.OrderBy(x => x.Doctor_Name).ToPagedList(page_no ?? 1, 10));
        }

        public ActionResult SelectDay(int id)
        {
            Session["action"] = "selectws";
            ViewBag.ID = id;
            return View();
        }

        public ActionResult GetCalendarData(int id)
        {
            JsonResult result = new JsonResult();

            try
            {
                List<Schedule> data = this.LoadData(id);
                
                result = this.Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Console.Write(ex);
            }

            return result;
        }

        private List<Schedule> LoadData(int id)
        {
            List<Schedule> lst = new List<Schedule>();

            try
            {
                var events = db.Working_Schedule.Where(a => a.Doctor_ID == id).ToList();
                
                foreach (var item in events)
                {
                    Schedule sch = new Schedule();

                    sch.Id = item.WorkingSchedule_ID;
                    sch.Title = item.Working_Time.WoringTime_Period;
                    sch.Desc = String.Concat(item.Doctor.Medical_Specialty.MedicalSpecialty_Name, " - ", item.Working_Day.WorkingDay_Period, " - ", 
                        item.Working_Time.WoringTime_Period, " - Room ", item.Working_Room.WorkingRoom_Number);
                    sch.Start_Date = item.Start.ToString();
                    sch.End_Date = item.End.ToString();
                    sch.Color = item.ThemeColor;
                    sch.AllDay = item.IsFullDay;

                    lst.Add(sch);
                }
            }
            catch (Exception ex)
            {
                Console.Write(ex);
            }

            return lst;
        }
    }
}

ProjectMedic/Views/VisitByDoctor/Index.cshtml
@model PagedList.IPagedList<ProjectMedic.Models.vDoctor>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_CustomerLayout2.cshtml";
}

<link href="/Content/PagedList.css" rel="stylesheet" />

@{
    int i = 0;
}

<table class="table">
    <tr>
        <th>
            No
        </th>
        <th>
            ACADEMIC TITLE
        </th>
        <th>
            DOCTOR
        </th>
        <th>
            GENDER
        </th>
        <th>
            MEDICAL SPECIALTY
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        i = i + 1;
        <tr>
            <td>
                @i
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AcademicTitle_Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Doctor_Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MedicalSpecialty_Name)
            </td>
            <td>
                <a href="@Url.Action("SelectDay", "VisitByDoctor", new { id = item.Doctor_ID })" class="btn btn-primary btn-sm">Select</a>
            </td>
        </tr>
    }
</table>
<br />

<div class="container-fluid">
    <h6 style="color:#007BFF">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</h6>

    @Html.PagedListPager(Model, page_no => Url.Action("Index", new
    {
        page_no,
        search = Request.QueryString["search"],
        ddl1 = Request.QueryString["ddl1"],
        ddl2 = Request.QueryString["ddl2"],
        ddl3 = Request.QueryString["ddl3"]
    }),
        new PagedListRenderOptions
        {
            DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded,
            DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded,
            DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
            DisplayLinkToNextPage = PagedListDisplayMode.Always,
            MaximumPageNumbersToDisplay = 3
        })
</div>

ProjectMedic/Views/VisitByDoctor/SelectDay.cshtml
@model IEnumerable<ProjectMedic.Models.Working_Day>

@{
    ViewBag.Title = "SelectDay";
    Layout = "~/Views/Layout/_CustomerLayout2.cshtml";
}

<div id='calender'></div>

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title"><span id="eventTitle"></span></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <p id="pDetails"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnSend">Make Appointment</button>
                <button type="button" class="btn btn-dark" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />

@section Scripts{
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>

    <script>
        $(document).ready(function () {
            var events = [];
            var selectedEvent = null;
            FetchEventAndRenderCalendar();

            function FetchEventAndRenderCalendar() {
                events = [];
                $.ajax({
                    type: "GET",
                    url: "/VisitByDoctor/GetCalendarData",
                    dataType: "JSON",
                    data: { id: @ViewBag.ID },
                    success: function (data) {
                        $.each(data, function (i, v) {
                            events.push({
                                eventID: v.Id,
                                title: v.Title,
                                description: v.Desc,
                                start: moment(v.Start_Date),
                                end: v.End_Date != null ? moment(v.End_Date) : null,
                                color: v.Color,
                                allDay: v.AllDay
                            });
                        })

                        GenerateCalender(events);
                    },
                    error: function (error) {
                        alert('failed');
                    }
                })
            }

            function GenerateCalender(events) {
                $('#calender').fullCalendar('destroy');
                $('#calender').fullCalendar({
                    contentHeight: 500,
                    //defaultDate: new Date(),
                    timeFormat: 'h(:mm)a',
                    header: {
                        left: 'today',
                        center: 'prev title next',
                        right: ''
                    },
                    eventLimit: false,
                    editable: true,
                    displayEventTime: false,
                    //navLinks: true,
                    //textColor: '#007BFF',
                    eventTextColor: 'white',
                    events: events,
                    eventClick: function (calEvent, jsEvent, view) {
                        selectedEvent = calEvent;
                        $('#myModal #eventTitle').text(calEvent.title);
                        var $description = $('<div/>');
                        $description.append($('<p/>').html('<b>Start: </b>' + calEvent.start.format("DD-MMM-YYYY HH:mm a")));
                        if (calEvent.end != null) {
                            $description.append($('<p/>').html('<b>End: </b>' + calEvent.end.format("DD-MMM-YYYY HH:mm a")));
                        }
                        $description.append($('<p/>').html('<b>Description: </b>' + calEvent.description));
                        $('#myModal #pDetails').empty().html($description);
                        $('#myModal').modal();
                    }
                })
            }

            $('#btnSend').click(function () {
                if (selectedEvent != null) {
                    $.ajax({
                        type: 'GET',
                        url: '/Appointment/AddAppointment',
                        data: { eventID: selectedEvent.eventID },
                        success: function () {
                                //$('#myModal').modal('hide');
                                window.location.href = '@Url.Action("Appointment", "Appointment")';
                        }
                    })
                }
            })
        })
    </script>
}