ProjectMedic/Models/Doctor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectMedic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Working_Schedule = new HashSet<Working_Schedule>();
        }
    
        public int Doctor_ID { get; set; }
        public string Doctor_Name { get; set; }
        public string Doctor_Gender { get; set; }
        public int AcademicTitle_ID { get; set; }
        public int MedicalSpecialty_ID { get; set; }
    
        public virtual Academic_Title Academic_Title { get; set; }
        public virtual Medical_Specialty Medical_Specialty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Working_Schedule> Working_Schedule { get; set; }
    }
}

ProjectMedic/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectMedic.Models;

namespace ProjectMedic.Controllers
{
    public class DoctorsController : Controller
    {
        private MediPlusEntities db = new MediPlusEntities();

        // GET: Doctors
        public ActionResult Index(int? page)
        {
            var doctors = db.Doctors.Include(d => d.Academic_Title).Include(d => d.Medical_Specialty);
            return View(doctors.ToList());
        }

        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            ViewBag.AcademicTitle_ID = new SelectList(db.Academic_Title, "AcademicTitle_ID", "AcademicTitle_Code");
            ViewBag.MedicalSpecialty_ID = new SelectList(db.Medical_Specialty, "MedicalSpecialty_ID", "MedicalSpecialty_Name");
            return View();
        }

        // POST: Doctors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Doctor_ID,Doctor_Name,Doctor_Gender,AcademicTitle_ID,MedicalSpecialty_ID")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AcademicTitle_ID = new SelectList(db.Academic_Title, "AcademicTitle_ID", "AcademicTitle_Code", doctor.AcademicTitle_ID);
            ViewBag.MedicalSpecialty_ID = new SelectList(db.Medical_Specialty, "MedicalSpecialty_ID", "MedicalSpecialty_Name", doctor.MedicalSpecialty_ID);
            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            ViewBag.AcademicTitle_ID = new SelectList(db.Academic_Title, "AcademicTitle_ID", "AcademicTitle_Code", doctor.AcademicTitle_ID);
            ViewBag.MedicalSpecialty_ID = new SelectList(db.Medical_Specialty, "MedicalSpecialty_ID", "MedicalSpecialty_Name", doctor.MedicalSpecialty_ID);
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Doctor_ID,Doctor_Name,Doctor_Gender,AcademicTitle_ID,MedicalSpecialty_ID")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AcademicTitle_ID = new SelectList(db.Academic_Title, "AcademicTitle_ID", "AcademicTitle_Code", doctor.AcademicTitle_ID);
            ViewBag.MedicalSpecialty_ID = new SelectList(db.Medical_Specialty, "MedicalSpecialty_ID", "MedicalSpecialty_Name", doctor.MedicalSpecialty_ID);
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectMedic/Views/Doctors/Create.cshtml
@model ProjectMedic.Models.Doctor

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add New Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Doctor_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doctor_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doctor_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doctor_Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doctor_Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doctor_Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AcademicTitle_ID, "AcademicTitle_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AcademicTitle_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AcademicTitle_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedicalSpecialty_ID, "MedicalSpecialty_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MedicalSpecialty_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MedicalSpecialty_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                <a href=@Url.Action("Index","Doctors") class="btn btn-default">Back to List</a>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ProjectMedic/Views/Doctors/Delete.cshtml
@model ProjectMedic.Models.Doctor

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<div>
    <h4>Are you sure you want to delete this?</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Doctor_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doctor_Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor_Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Academic_Title.AcademicTitle_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Academic_Title.AcademicTitle_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Medical_Specialty.MedicalSpecialty_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medical_Specialty.MedicalSpecialty_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
        <a href=@Url.Action("Index","Doctors") class="btn btn-default">Back to List</a>
    </div>
    }
</div>

ProjectMedic/Views/Doctors/Details.cshtml
@model ProjectMedic.Models.Doctor

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<div>
    <h4>Doctor Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Doctor_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doctor_Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doctor_Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Academic_Title.AcademicTitle_Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Academic_Title.AcademicTitle_Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Medical_Specialty.MedicalSpecialty_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Medical_Specialty.MedicalSpecialty_Name)
        </dd>

    </dl>
</div>
<p>
    <a href=@Url.Action("Edit","Doctors", new { id = Model.Doctor_ID }) class="btn btn-default">Edit</a>
    <a href=@Url.Action("Index","Doctors") class="btn btn-default">Back to List</a>
</p>

ProjectMedic/Views/Doctors/Edit.cshtml
@model ProjectMedic.Models.Doctor

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Edit Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Doctor_ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Doctor_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doctor_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doctor_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Doctor_Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Doctor_Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Doctor_Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AcademicTitle_ID, "AcademicTitle_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AcademicTitle_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AcademicTitle_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MedicalSpecialty_ID, "MedicalSpecialty_ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MedicalSpecialty_ID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MedicalSpecialty_ID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
                <a href=@Url.Action("Index","Doctors") class="btn btn-default">Back to List</a>
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

ProjectMedic/Views/Doctors/Index.cshtml
@model IEnumerable<ProjectMedic.Models.Doctor>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<h2>Doctor List</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Doctor_Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Doctor_Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Academic_Title.AcademicTitle_Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Medical_Specialty.MedicalSpecialty_Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Doctor_Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Doctor_Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Academic_Title.AcademicTitle_Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Medical_Specialty.MedicalSpecialty_Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Doctor_ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.Doctor_ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Doctor_ID })
        </td>
    </tr>
}

</table>