ProjectMedic/Controllers/VisitByDateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectMedic.Models;
using PagedList;

namespace ProjectMedic.Controllers
{
    public class VisitByDateController : Controller
    {
        MediPlusEntities db = new MediPlusEntities();
        // GET: VisitByDate
        public ActionResult Index()
        {
            if(Session["P_ID"] == null)
            {
                return RedirectToAction("TermOfService", "Home");
            }
            else
            {
                Session["action"] = "selectday";
                return View();
            }
        }

        public ActionResult GetDate(string date, int dayofweek)
        {
            Session["date"] = date;
            switch (dayofweek)
            {
                case 0:
                    Session["dayofweek"] = "Sunday";
                    break;
                case 1:
                    Session["dayofweek"] = "Monday";
                    break;
                case 2:
                    Session["dayofweek"] = "Tuesday";
                    break;
                case 3:
                    Session["dayofweek"] = "Wednesday";
                    break;
                case 4:
                    Session["dayofweek"] = "Thursday";
                    break;
                case 5:
                    Session["dayofweek"] = "Friday";
                    break;
                case 6:
                    Session["dayofweek"] = "Saturday";
                    break;
            }
            return null;
        }

        public ActionResult SelectMedicalSpecialty(int? page_no, string search)
        {
            Session["action"] = "selectms";

            var ms = db.Medical_Specialty.AsQueryable();

            if (!String.IsNullOrEmpty(search))
            {
                ms = ms.Where(m => m.MedicalSpecialty_Name.ToLower().Contains(search));
            }

            return View(ms.OrderBy(a => a.MedicalSpecialty_Name).ToPagedList(page_no ?? 1, 5));
        }

        public ActionResult SelectDoctor(string ms)
        {
            Session["action"] = "getdoctor";
            var doctors = db.vDoctors.Where(d => d.MedicalSpecialty_Name.Equals(ms));

            List<SelectListItem> list = new List<SelectListItem>();
            foreach (var item in db.Working_Time)
            {
                list.Add(new SelectListItem()
                {
                    Text = item.WoringTime_Period.ToString(),
                    Value = item.WorkingTime_ID.ToString()
                });
            }
            ViewBag.WT = list;

            return View(doctors.ToList());
        }

        public ActionResult SaveShedule()
        {
            return RedirectToAction("");
        }
    }
}

ProjectMedic/Views/VisitByDate/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_CustomerLayout2.cshtml";
}

<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css" rel="stylesheet" />
<link href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.print.css" rel="stylesheet" media="print" />

<div id='calender'></div>

@section Scripts{
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>

    <script>
        $(document).ready(function () {
            GenerateCalender();

            function GenerateCalender() {
                $('#calender').fullCalendar('destroy');
                $('#calender').fullCalendar({
                    selectable: true,
                    contentHeight: 500,
                    timeFormat: 'h(:mm)a',
                    header: {
                        left: 'today',
                        center: 'prev title next',
                        right: ''
                    },
                    eventLimit: false,
                    editable: true,
                    displayEventTime: false,
                    eventTextColor: 'white',

                    dayClick: function (date) {
                        if (moment().format('YYYY-MM-DD') === date.format('YYYY-MM-DD') || date.isAfter(moment())) {
                            // This allows today and future date
                            $.ajax({
                                type: 'GET',
                                url: '/VisitByDate/GetDate',
                                data: { date: date.format(), dayofweek: date.day() },
                                success: function () {
                                    window.location.href = '@Url.Action("SelectMedicalSpecialty", "VisitByDate")';
                                },
                                error: function () {
                                    alert('fail')
                                }
                            })
                        } else {
                            // Else part is for past dates
                        }
                    }
                })
            }
        })
    </script>
}

ProjectMedic/Views/VisitByDate/SelectDoctor.cshtml
@model List<ProjectMedic.Models.vDoctor>

@{
    ViewBag.Title = "SeclectDoctor";
    Layout = "~/Views/Layout/_CustomerLayout2.cshtml";
}

@{
    int i = 0;
    Random rd = new Random();
}

<div class="panel-group" id="accordion">

    @foreach (var item in Model)
    {
        i = i + 1;
        int room = rd.Next(1, 42);
        <div class="panel panel-default" style="border: 2px solid #007BFF; padding:10px; margin-bottom:20px; background-color:white; box-shadow: 5px 10px 18px #888888">
            <div class="panel-heading">
                <label>Doctor: @item.AcademicTitle_Code @item.Doctor_Name</label><br />
                <label>Gender: @item.Doctor_Gender</label><br />
                <label>Medical Specialty: @item.MedicalSpecialty_Name</label><br />
                <label>Room: <span>0</span>@room</label>
                <a data-toggle="collapse" data-parent="#accordion" href="#@i" class="btn btn-primary" style="margin-left:785px; width:150px">Select</a>
            </div>
            <div id="@i" class="panel-collapse collapse" style="border-top: 2px dotted #007BFF; margin-left: -10px; margin-right: -10px; margin-top:10px">
                <div class="panel-body" style="margin:10px">
                    @using (Html.BeginForm("AddSchedule", "Appointment", new { @ms = item.MedicalSpecialty_Name, @dt = item.Doctor_Name, @dt_id = item.Doctor_ID, @ro = room }))
                    {
                        <label>Choose Visit Time</label>
                        @Html.DropDownList("ddl", (IEnumerable<SelectListItem>)ViewBag.WT, htmlAttributes: new { @class = "form-control" })
                        <button type="submit" class="btn btn-primary" style="margin-left:785px; width:150px; margin-top:10px">Continue</button>
                    }
                </div>
            </div>
        </div>
    }

</div>

ProjectMedic/Views/VisitByDate/SelectMedicalSpecialty.cshtml
@model PagedList.IPagedList<ProjectMedic.Models.Medical_Specialty>
@using PagedList.Mvc;

@{
    ViewBag.Title = "SelectMedicalSpecialty";
    Layout = "~/Views/Layout/_CustomerLayout2.cshtml";
}

<link href="/Content/PagedList.css" rel="stylesheet" />

@{
    int i = 0;
}

<table class="table">
    <tr>
        <th style="width:80px">No</th>
        <th style="width:540px">MEDICAL SPECIALTY</th>
        <th style="width:150px">SERVICE PRICE</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        i = i + 1;
        <tr>
            <td>@i</td>
            <td>@item.MedicalSpecialty_Name</td>
            <td>$ @String.Format("{0:0,0}", item.MedicalSpecialty_ServicePrice)</td>
            <td><a href="@Url.Action("SelectDoctor","VisitByDate", new { ms = item.MedicalSpecialty_Name })" class="btn btn-primary">Select</a></td>
        </tr>
    }
</table>

<div class="container-fluid">
    <h6 style="color:#007BFF">Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount</h6>

    @Html.PagedListPager(Model, page_no => Url.Action("SelectMedicalSpecialty", new
    {
        page_no,
        search = Request.QueryString["search"]
    }),
                    new PagedListRenderOptions
                    {
                        DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded,
                        DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded,
                        DisplayLinkToPreviousPage = PagedListDisplayMode.Always,
                        DisplayLinkToNextPage = PagedListDisplayMode.Always,
                        MaximumPageNumbersToDisplay = 3
                    })
</div>